"""Library builder that scans pattern repos and generates dist outputs."""

import json
import os
from typing import List, Dict, Any
from .pat_parser import parse_pat_file
from .json_parser import parse_json_beat_file
from .strudel_generator import (
    generate_strudel_snippet,
    generate_channel_snippet,
    generate_js_library_entry,
    sanitize_js_identifier,
)


def scan_patterns(drum_patterns_dir: str, drum_beat_repo_dir: str) -> List[Dict[str, Any]]:
    """Scan both repositories and return a list of all parsed patterns."""
    patterns = []
    
    # 1. Scan drum-patterns (.pat files)
    if os.path.exists(drum_patterns_dir):
        for root, _, files in os.walk(drum_patterns_dir):
            for file in sorted(files):
                if file.endswith(".pat"):
                    full_path = os.path.join(root, file)
                    try:
                        pat = parse_pat_file(full_path, repo_root=drum_patterns_dir)
                        if pat.get("tracks"):
                            patterns.append(pat)
                    except Exception as e:
                        print(f"Warning: Failed to parse {full_path}: {e}")
                        
    # 2. Scan DrumBeatRepo (.json files in frontend/src/assets/beats)
    beats_dir = os.path.join(drum_beat_repo_dir, "frontend", "src", "assets", "beats")
    if os.path.exists(beats_dir):
        for root, _, files in os.walk(beats_dir):
            for file in sorted(files):
                if file.endswith(".json"):
                    full_path = os.path.join(root, file)
                    try:
                        pat = parse_json_beat_file(full_path)
                        if pat.get("tracks"):
                            patterns.append(pat)
                    except Exception as e:
                        print(f"Warning: Failed to parse {full_path}: {e}")
                        
    return patterns


def build_library(
    drum_patterns_dir: str,
    drum_beat_repo_dir: str,
    output_dir: str = "dist",
    default_bank: str = "RolandTR808"
):
    """Scan repos and generate dist/strudel_library.js, dist/strudel_library.json, dist/CATALOG.md."""
    os.makedirs(output_dir, exist_ok=True)
    
    patterns = scan_patterns(drum_patterns_dir, drum_beat_repo_dir)
    print(f"Total patterns found: {len(patterns)}")
    
    # Group patterns by category/genre
    categories: Dict[str, List[Dict[str, Any]]] = {}
    for pat in patterns:
        cat = pat.get("category", "General")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(pat)
        
    # --- 1. Build dist/strudel_library.json ---
    json_output_path = os.path.join(output_dir, "strudel_library.json")
    json_data = []
    for pat in patterns:
        pat_copy = dict(pat)
        pat_copy["strudel_snippet"] = generate_strudel_snippet(pat, default_bank=default_bank)
        pat_copy["channel_snippet"] = generate_channel_snippet(pat, default_bank=default_bank)
        json_data.append(pat_copy)
        
    with open(json_output_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)
    print(f"Generated JSON dataset: {json_output_path}")

    # --- 2. Build dist/strudel_library.js ---
    js_output_path = os.path.join(output_dir, "strudel_library.js")
    js_lines = [
        "// Strudel Drum Pattern Library Export",
        "// Auto-generated by strudel_converter",
        "",
        "setcpm(140 / 4);",
        f'const kit = "{default_bank}";',
        'const bass_key = "c";',
        'const bass_octave = 1;',
        'const bass_synth = "sawtooth";',
        "",
        "const drumLibrary = {"
    ]
    
    cat_blocks = []
    for cat_name, cat_pats in sorted(categories.items()):
        cat_key = sanitize_js_identifier(cat_name)
        pat_entries = []
        for pat in cat_pats:
            pat_key = sanitize_js_identifier(pat["name"])
            js_entry = generate_js_library_entry(pat, default_bank=default_bank)
            pat_entries.append(f"    // {pat['name']}\n    {pat_key}: {js_entry}")
            
        inner_pats = ",\n\n".join(pat_entries)
        cat_blocks.append(f"  // Category: {cat_name}\n  {cat_key}: {{\n{inner_pats}\n  }}")
        
    js_lines.append(",\n\n".join(cat_blocks))
    js_lines.append("};")
    js_lines.append("")
    js_lines.append("// Helper function to play any pattern with a given bank")
    js_lines.append("function playPattern(pattern, bank = kit) {")
    js_lines.append("  if (typeof pattern === 'function') return pattern(bank);")
    js_lines.append("  return pattern;")
    js_lines.append("}")
    js_lines.append("")
    js_lines.append("if (typeof globalThis !== 'undefined') {")
    js_lines.append("  globalThis.drumLibrary = drumLibrary;")
    js_lines.append("  globalThis.playPattern = playPattern;")
    js_lines.append("}")
    js_lines.append("")
    js_lines.append("export { kit, bass_key, bass_octave, bass_synth, drumLibrary, playPattern };")
    
    with open(js_output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(js_lines))
    print(f"Generated JavaScript library: {js_output_path}")

    # --- 3. Build dist/CATALOG.md ---
    md_output_path = os.path.join(output_dir, "CATALOG.md")
    md_lines = [
        "# Strudel Drum Patterns Catalog 🥁",
        "",
        f"Total patterns: **{len(patterns)}** across **{len(categories)}** categories.",
        "",
        "Import or copy any snippet directly into [Strudel.cc](https://strudel.cc).",
        "",
        "---",
        ""
    ]
    
    for cat_name, cat_pats in sorted(categories.items()):
        md_lines.append(f"## {cat_name}")
        md_lines.append("")
        for pat in cat_pats:
            md_lines.append(f"### {pat['name']}")
            if pat.get("bpm"):
                md_lines.append(f"**BPM:** {pat['bpm']}")
            md_lines.append(f"**Source:** {pat['source']}")
            md_lines.append("")
            md_lines.append("```js")
            md_lines.append(generate_strudel_snippet(pat, default_bank=default_bank))
            md_lines.append("```")
            md_lines.append("")
            md_lines.append("<details><summary>View Live Channel Mode ($:)</summary>")
            md_lines.append("")
            md_lines.append("```js")
            md_lines.append(generate_channel_snippet(pat, default_bank=default_bank))
            md_lines.append("```")
            md_lines.append("</details>")
            md_lines.append("")
        md_lines.append("---")
        md_lines.append("")
        
    with open(md_output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))
    print(f"Generated Markdown catalog: {md_output_path}")
