"""Library builder that scans pattern repos and generates dist outputs."""

import json
import os
from typing import List, Dict, Any
from .pat_parser import parse_pat_file
from .json_parser import parse_json_beat_file
from .strudel_generator import (
    generate_strudel_snippet,
    generate_channel_snippet,
    extract_pattern_tracks_dict,
    sanitize_js_identifier,
)


def scan_patterns(drum_patterns_dir: str, drum_beat_repo_dir: str) -> List[Dict[str, Any]]:
    """Scan both repositories and return a list of all parsed patterns."""
    patterns = []
    
    # 1. Scan drum-patterns (.pat files)
    if os.path.exists(drum_patterns_dir):
        for root, _, files in os.walk(drum_patterns_dir):
            for file in sorted(files):
                if file.endswith(".pat"):
                    full_path = os.path.join(root, file)
                    try:
                        pat = parse_pat_file(full_path, repo_root=drum_patterns_dir)
                        if pat.get("tracks"):
                            patterns.append(pat)
                    except Exception as e:
                        print(f"Warning: Failed to parse {full_path}: {e}")
                        
    # 2. Scan DrumBeatRepo (.json files in frontend/src/assets/beats)
    beats_dir = os.path.join(drum_beat_repo_dir, "frontend", "src", "assets", "beats")
    if os.path.exists(beats_dir):
        for root, _, files in os.walk(beats_dir):
            for file in sorted(files):
                if file.endswith(".json"):
                    full_path = os.path.join(root, file)
                    try:
                        pat = parse_json_beat_file(full_path)
                        if pat.get("tracks"):
                            patterns.append(pat)
                    except Exception as e:
                        print(f"Warning: Failed to parse {full_path}: {e}")
                        
    return patterns


def build_library(
    drum_patterns_dir: str,
    drum_beat_repo_dir: str,
    output_dir: str = "dist",
    default_bank: str = "RolandTR808"
):
    """Scan repos and generate dist/strudel_library.js, dist/strudel_library.json, dist/CATALOG.md."""
    os.makedirs(output_dir, exist_ok=True)
    
    patterns = scan_patterns(drum_patterns_dir, drum_beat_repo_dir)
    print(f"Total patterns found: {len(patterns)}")
    
    # Group patterns by category/genre
    categories: Dict[str, List[Dict[str, Any]]] = {}
    for pat in patterns:
        cat = pat.get("category", "General")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(pat)
        
    # --- 1. Build dist/strudel_library.json ---
    json_output_path = os.path.join(output_dir, "strudel_library.json")
    json_data = []
    for pat in patterns:
        pat_copy = dict(pat)
        pat_copy["strudel_snippet"] = generate_strudel_snippet(pat, default_bank=default_bank)
        pat_copy["channel_snippet"] = generate_channel_snippet(pat, default_bank=default_bank)
        pat_copy["tracks_data"] = extract_pattern_tracks_dict(pat)
        json_data.append(pat_copy)
        
    with open(json_output_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)
    print(f"Generated JSON dataset: {json_output_path}")

    # --- 2. Build dist/strudel_library.js ---
    js_output_path = os.path.join(output_dir, "strudel_library.js")
    js_lines = [
        "// Strudel Drum Pattern Library Export",
        "// Auto-generated by strudel_converter",
        "",
        "const _patterns = {};"
    ]
    
    # Export flat raw pattern data dicts as plain JS objects with play(opts) methods
    for pat in patterns:
        cat_key = sanitize_js_identifier(pat["category"])
        pat_key = sanitize_js_identifier(pat["name"])
        unique_func_key = f"{cat_key}_{pat_key}"
        data_dict = extract_pattern_tracks_dict(pat)
        json_str = json.dumps(data_dict)
        
        js_lines.append(f"_patterns.{unique_func_key} = Object.assign({json_str}, {{")
        js_lines.append(f"  play(opts) {{ return play(this, opts); }}")
        js_lines.append("});")
        js_lines.append(f"_patterns.{pat_key} = _patterns.{unique_func_key};")
        
    js_lines.append("")
    js_lines.append("const drumLibrary = {};")
    
    for cat_name, cat_pats in sorted(categories.items()):
        cat_key = sanitize_js_identifier(cat_name)
        first_pat = cat_pats[0]
        first_func_key = f"{cat_key}_{sanitize_js_identifier(first_pat['name'])}"
        
        matching = [p for p in cat_pats if sanitize_js_identifier(p["name"]) == cat_key]
        primary_func_key = f"{cat_key}_{sanitize_js_identifier(matching[0]['name'])}" if matching else first_func_key
        
        sub_entries = []
        for pat in cat_pats:
            pat_key = sanitize_js_identifier(pat["name"])
            u_key = f"{cat_key}_{pat_key}"
            sub_entries.append(f"    {pat_key}: _patterns.{u_key}")
        inner_subs = ",\n".join(sub_entries)

        js_lines.append(f"drumLibrary.{cat_key} = Object.assign(")
        js_lines.append(f"  {{ title: {json.dumps(cat_name)}, play(opts) {{ return play(_patterns.{primary_func_key}, opts); }},")
        js_lines.append(f"{inner_subs} }},")
        js_lines.append(f"  _patterns.{primary_func_key}")
        js_lines.append(");")
        
        for pat in cat_pats:
            pat_key = sanitize_js_identifier(pat["name"])
            u_key = f"{cat_key}_{pat_key}"
            js_lines.append(f"if (!drumLibrary.{pat_key}) drumLibrary.{pat_key} = _patterns.{u_key};")
            
    js_lines.append("")
    js_lines.append("// play(pattern, opts) - plays a pattern using Strudel's REPL functions")
    js_lines.append("// opts: { bank, n, key, octave, synth, s, stack }")
    js_lines.append("// NOTE: bd/sd/hh etc are built-in Strudel defaults (no bank needed).")
    js_lines.append("// Use bank:'RolandTR808' to switch to a specific drum machine.")
    js_lines.append("function play(pattern, opts = {}) {")
    js_lines.append("  const o = typeof opts === 'string' ? { bank: opts } : (opts || {});")
    js_lines.append("  const pat = typeof pattern === 'string' ? (drumLibrary[pattern] || _patterns[pattern]) : pattern;")
    js_lines.append("  if (!pat || !pat.tracks) return pat;")
    js_lines.append("")
    js_lines.append("  // bank is OPTIONAL - omit to use Strudel built-in default samples (bd, sd, hh etc)")
    js_lines.append("  const bank = o.bank || o.kit || null;")
    js_lines.append("  const n = o.n;")
    js_lines.append("  const key = o.key || o.bassKey || 'c';")
    js_lines.append("  const oct = o.octave || o.bassOctave || 1;")
    js_lines.append("  const validSynths = ['sawtooth', 'square', 'sine', 'triangle', 'supersaw'];")
    js_lines.append("  const rawSynth = (o.synth || o.bassSynth || 'sawtooth').toString().toLowerCase();")
    js_lines.append("  const synth = validSynths.includes(rawSynth) ? rawSynth : 'sawtooth';")
    js_lines.append("")
    js_lines.append("  const sFn = o.s || (typeof s === 'function' ? s : (typeof globalThis.s === 'function' ? globalThis.s : null));")
    js_lines.append("  const stackFn = o.stack || (typeof stack === 'function' ? stack : (typeof globalThis.stack === 'function' ? globalThis.stack : null));")
    js_lines.append("")
    js_lines.append("  if (!sFn || !stackFn) return pat;")
    js_lines.append("")
    js_lines.append("  const stackTracks = [];")
    js_lines.append("  for (const [instrument, miniPat] of Object.entries(pat.tracks)) {")
    js_lines.append("    let t;")
    js_lines.append("    if (instrument === 'bass' || instrument === 'synth') {")
    js_lines.append("      t = sFn(synth).note(key).octave(oct).decay(0.2).sustain(0).struct(miniPat);")
    js_lines.append("    } else {")
    js_lines.append("      t = sFn(instrument).struct(miniPat);")
    js_lines.append("      const nVal = typeof n === 'object' ? (n[instrument] ?? null) : (typeof n === 'number' ? n : null);")
    js_lines.append("      if (nVal !== null) t = t.n(nVal);")
    js_lines.append("      if (bank) t = t.bank(bank);")
    js_lines.append("    }")
    js_lines.append("")
    js_lines.append("    if (pat.gains && pat.gains[instrument]) {")
    js_lines.append("      t = t.gain(pat.gains[instrument]);")
    js_lines.append("    }")
    js_lines.append("    stackTracks.push(t);")
    js_lines.append("  }")
    js_lines.append("")
    js_lines.append("  return stackFn(...stackTracks);")
    js_lines.append("}")
    js_lines.append("")
    js_lines.append("if (typeof globalThis !== 'undefined') {")
    js_lines.append("  globalThis.drumLibrary = drumLibrary;")
    js_lines.append("  globalThis.play = play;")
    js_lines.append("}")
    js_lines.append("")
    js_lines.append("export { drumLibrary, play };")
    
    with open(js_output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(js_lines))
    print(f"Generated JavaScript library: {js_output_path}")

    # --- 3. Build dist/CATALOG.md ---
    md_output_path = os.path.join(output_dir, "CATALOG.md")
    md_lines = [
        "# Strudel Drum Patterns Catalog 🥁",
        "",
        f"Total patterns: **{len(patterns)}** across **{len(categories)}** categories.",
        "",
        "Import or copy any snippet directly into [Strudel.cc](https://strudel.cc).",
        "",
        "---",
        ""
    ]
    
    for cat_name, cat_pats in sorted(categories.items()):
        md_lines.append(f"## {cat_name}")
        md_lines.append("")
        for pat in cat_pats:
            md_lines.append(f"### {pat['name']}")
            if pat.get("bpm"):
                md_lines.append(f"**BPM:** {pat['bpm']}")
            md_lines.append(f"**Source:** {pat['source']}")
            md_lines.append("")
            md_lines.append("```js")
            md_lines.append(generate_strudel_snippet(pat, default_bank=default_bank))
            md_lines.append("```")
            md_lines.append("")
            md_lines.append("<details><summary>View Live Channel Mode ($:)</summary>")
            md_lines.append("")
            md_lines.append("```js")
            md_lines.append(generate_channel_snippet(pat, default_bank=default_bank))
            md_lines.append("```")
            md_lines.append("</details>")
            md_lines.append("")
        md_lines.append("---")
        md_lines.append("")
        
    with open(md_output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))
    print(f"Generated Markdown catalog: {md_output_path}")
